### ISSUE TITLE
More changes from teamhackback

### ISSUE THREAD

**Issue by wilzbach** [thaven/oauth#4]
Hi there,

I saw your nice OAuth module and as you have seen I liked it so much that I have forked it at https://github.com/teamhackback/oauth

I have done a couple of further changes and due to the split of `client.d` into multiple files a PR might be long. However if you are interested I am happy to look into cleaning the changes and incorporating them into a PR. I also plan to publish a bigger example app in the next weeks.

Here's an overview of major changes:

Bug fixes
-------------

- properly remove "oauth.session": https://github.com/teamhackback/oauth/commit/a0e0c359b2c2ccc65bc7f0d87767b6320bbe76c0 (based on https://github.com/rejectedsoftware/vibe.d/pull/1670)
- Add `.dup` to  `sha256Of(base);` - for some weird reason the allocated memory seems to change
- Add redirect by default: https://github.com/teamhackback/oauth/commit/018aa4b7e328b5ae2d393468ff49740dcb1e65ea

Other changes
--------------------

- Split `client.d` into `exception.d`, `session.d`, `settings.d`  (`config.d` is part of `settings.d`)
- Made [a lot of stuff `@safe`](https://github.com/teamhackback/oauth/commit/47caa10d9717a59a8a21d3e63b564bdedf18d488) for Vibe.d 0.8
- Add GitHub provider
- Load config from environment
- Added minimal logging
- Added `extraParams` to `webapp.login`
- Changed return type of `webapp.login` to `bool`

Removed caching from Webapp convience wrapper
---------------------------------------------------------------------

As I want to deploy my application on multiple servers/threads a cache is problematic as the second request might hit another thread / server. Moreover a long-running application also needs some auto-cleanup, which currently isn't implemented. Thus I removed both `settingsCache` and `sessionCache`.

**Comment by thaven** [comment]
Your contribution is very much appreciated. I had a quick look at it, and most looks good, though a bit messy commit-wise. I'll just pick usable changes, taking care of correct authorship of commits.

**Comment by thaven** [comment]
The redirect_uri parameter not being set by default is not a bug. RFC 6749 clearly states it's optional. If omitted, the authorization server should use the redirect_uri known for the client.

**Comment by thaven** [comment]
@wilzbach A lot of your changes made it into master, but some things have been done a slightly different way. Also I did not include the logging yet, but logging will still be added somehow.

Can you have a look if current master works for you?

**Comment by wilzbach** [comment]
> @wilzbach A lot of your changes made it into master, but some things have been done a slightly different way.

Awesome. Thanks a lot & sorry for being so unresponsive.

> Also I did not include the logging yet, but logging will still be added somehow.

Opened https://github.com/thaven/oauth/issues/7, s.t. it's not forgotten.

> Can you have a look if current master works for you?

I finally found time to resync my master with your upstream & everything looks every good except for a couple of changes in `webapp.d` (I will open a PR soon).

**Comment by wilzbach** [comment]
> I finally found time to resync my master with your upstream & everything looks every good except for a couple of changes in webapp.d (I will open a PR soon).

-> https://github.com/thaven/oauth/pull/9
